### PR TITLE
E57 reader updates

### PR DESCRIPTION
**Pull request by pravinshinde825**

### CODE REVIEW

**Comment by pravinshinde825** [comment]
@nicolas-chaulet ,
I've added Scan and inspect() back. Scan class is a bit modified.

**Review by nicolas-chaulet — CHANGES_REQUESTED** [review]
I tried to compile on my machine and I have the following warnings and error:
```
In file included from /Volumes/Workspace/PDAL/plugins/e57/io/E57Reader.cpp:35:
/Volumes/Workspace/PDAL/plugins/e57/io/E57Reader.hpp:52:17: warning: 'getName' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    std::string getName() const;
                ^
/Volumes/Workspace/PDAL/pdal/Stage.hpp:261:25: note: overridden virtual function is here
    virtual std::string getName() const = 0;
                        ^
/Volumes/Workspace/PDAL/plugins/e57/io/E57Reader.cpp:51:31: warning: field 'm_currentScan' will be initialized after field 'm_currentIndex' [-Wreorder]
    : Reader(), Streamable(), m_currentScan(-1), m_currentIndex(0),
                              ^
/Volumes/Workspace/PDAL/plugins/e57/io/E57Reader.cpp:232:19: error: non-const lvalue reference to type 'pdal::PointRef' cannot bind to a temporary of type 'pdal::PointRef'
        fillPoint(view->point(nextId));
                  ^~~~~~~~~~~~~~~~~~~
/Volumes/Workspace/PDAL/plugins/e57/io/E57Reader.cpp:195:37: note: passing argument to parameter 'point' here
bool E57Reader::fillPoint(PointRef& point)
                                    ^
```
Could you please fix?

**Comment by pravinshinde825** [comment]
I can build this on my Linux as well as Windows machine. Not Sure whats wrong at your end.
Last commit may fix this issue.

**Comment by pravinshinde825** [comment]
> I can build this on my Linux as well as Windows machine. Not Sure whats wrong at your end.
> Last commit may fix this issue.

Ok I reproduced and fixed this build issue.

**Review by nicolas-chaulet — APPROVED** [review]

**Pull request merged**
